# Generated by Django 3.1.2 on 2020-11-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_auto_20201101_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='minimum_accepted_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='startupproduct',
            name='predicted_score',
            field=models.FloatField(default=0),
        ),
    ]
