# Generated by Django 3.1.2 on 2020-11-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0003_auto_20201101_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='maximum_funding_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
