# Generated by Django 3.1.2 on 2020-11-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0004_auto_20201101_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_ceo',
            name='productType',
        ),
    ]
